language: python
sudo: false
env:
   global:
     - OFFICIAL_REPO="slaclab/skywalker"
     - secure: "t399QOE83FONpr3PslOu6E28TwJUr6Kywt8JYVae22JCp2l703KYru4Bw3VFOfJSv2A1BISrU5Q6z5xu8BU3qU9V9UtPX7r6iVnK/Jqhxh+jjLA2tglBDUfWLYABC27UgaqDyGs2b9K+q/5c1Fv7jUPiZ+a53ly7Zwg7pu679KvFhbhBhPooSGxkyY+OISNmNr2VF1E34BxzWEaqD0yqjX8DsJEvUjPRwhPxTCQ3h4+BahhXWVZD0+I64/ATvf/4dsjK5LJ9nQLWrgaK9zEklNOw4XHJDthCQ22s2Vx6VlCDmUeHQrGGtqOK2n0atPWr6tOGkRtu2r9RArUt92tcYWt8cUIBFGP18UBRvRBdYkhvqysIUgLA4TmbI/H0uMtHnmvJ3AVjb6oRLlfQWUwneMm+LcawdvVGmVh7Jbo3c7T6KUaL2YWkyUuoao2IshAhbB09OG5QYcIFAsB68COPhVoP9ck88+Z7QjpBGox9epJnBUYedTAyijX7e23XTOgTeSXKxv3tnYdVq8gLyjhcp2E53W3PplRjawAaCuyAgyFR14tniCV0Pc6XehPa2ANCLbuqWLCQZac5KyMQ4ENQMzWoIWD0+wGnaGdHLBDPcT0TZogE9uvdTbLMnhhQVRebXu3gbCDhWAzWTltU2QIyYBsCVGQMXmxDmo3zGHXJnBg="

matrix:
   include: 
      - python: 3.5
      - python: 3.6
        env: BUILD_DOCS=1

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda-build anaconda-client
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  #Grab all dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION coverage hypothesis=3.11.6 pip wheel swig pyqt=5 pytest happi=0.5.0 pcds-devices=0.2.0 lightpath=0.2.1 psbeam=0.0.3 pswalker=0.2.0  -c lightsource2-tag -c skywalker-tag -c conda-forge  -c pydm-dev -c gsecars
  #Launch Conda environment
  - source activate test-environment
  #Install requirements
  - pip install codecov
  #Install pydm
  - pip install git+https://github.com/slaclab/pydm
  #Install
  - python setup.py install

script:
  - coverage run run_tests.py
  - coverage report -m
  - set -e
  #Build docs
  - |
    if [[ -n "$DOCTR_DEPLOY_ENCRYPTION_KEY" && $BUILD_DOCS ]]; then
      pip install -r doc-requirements.txt
      # Install doctr from a custom branch until
      # https://github.com/drdoctr/doctr/pull/190 is merged.
      pip uninstall -y doctr
      pip install git+https://github.com/danielballan/doctr@other-master
      pushd docs
      make html
      popd
      #Publish docs.
      doctr deploy --deploy-repo lcls-pcds/skywalker-docs --deploy-branch-name master .
    fi

after_success:
  - codecov
  - |
    if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == $OFFICIAL_REPO && $TRAVIS_BRANCH == $TRAVIS_TAG  && $TRAVIS_TAG != '' && $CONDA_UPLOAD_TOKEN_TAG != '' ]]; then
      conda build . -c defaults -c conda-forge -c skywalker-dev -c lightsource2-tag -c paulscherrerinstitute --token $CONDA_UPLOAD_TOKEN_TAG --python $TRAVIS_PYTHON_VERSION
    fi
  - |
    if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == $OFFICIAL_REPO && $TRAVIS_BRANCH == 'master' && $TRAVIS_TAG == '' && $CONDA_UPLOAD_TOKEN_DEV != '' ]]; then
      conda build . -c defaults -c conda-forge -c skywalker-dev -c lightsource2-tag -c paulscherrerinstitute --token $CONDA_UPLOAD_TOKEN_DEV --python $TRAVIS_PYTHON_VERSION
    fi    
