{% set data = load_setup_py_data() %}

package:
    name    : skywalker
    version : {{ data.get('version') }}

source:
    path: ..

requirements:
    build:
       - python {{PY_VER}}*,>=3
       - setuptools

    run:
      - python {{PY_VER}}*,>=3
      - happi <=0.5.0
      - pcds-devices ==0.2.0
      - lightpath ==0.2.1
      - psbeam ==0.0.3
      - pswalker ==0.2.0
      - pyqt >=5
      - numpy

test:
    imports:
      - skywalker

about:
  home: https://github.com/slaclab/skywalker
  license: SLAC Open License
  summary: Automatic alignment module for LCLS mirror systems
